/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// MountTmpfsOptions - Optional configuration for the `tmpfs` type.
type MountTmpfsOptions struct {

	// The size for the tmpfs mount in bytes.
	SizeBytes int64 `json:"SizeBytes,omitempty"`

	// The permission mode for the tmpfs mount in an integer.
	Mode uint32 `json:"Mode,omitempty"`
}
