/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// NetworkStats
type NetworkStats struct {
	// Bytes received. Windows and Linux.
	RxBytes uint64 `json:"RxBytes,omitempty"`
	// Packets received. Windows and Linux.
	RxPackets uint64 `json:"RxPackets,omitempty"`
	// Received errors. Not used on Windows. Note that we don't `omitempty` this
	// field as it is expected in the >=v1.21 API stats structure.
	RxErrors uint64 `json:"RxErrors,omitempty"`
	// Incoming packets dropped. Windows and Linux.
	RxDropped uint64 `json:"RxDropped,omitempty"`
	// Bytes sent. Windows and Linux.
	TxBytes uint64 `json:"TxBytes,omitempty"`
	// Packets sent. Windows and Linux.
	TxPackets uint64 `json:"TxPackets,omitempty"`
	// Sent errors. Not used on Windows. Note that we don't `omitempty` this
	// field as it is expected in the >=v1.21 API stats structure.
	TxErrors uint64 `json:"TxErrors,omitempty"`
	// Outgoing packets dropped. Windows and Linux.
	TxDropped uint64 `json:"TxDropped,omitempty"`
	// Endpoint ID. Not used on Linux.
	EndpointId string `json:"EndpointId,omitempty"`
	// Instance ID. Not used on Linux.
	InstanceId string `json:"InstanceId,omitempty"`
}
