/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// DeviceRequest - A request for devices to be sent to device drivers
type DeviceRequest struct {
	Driver string `json:"Driver,omitempty"`

	Count int `json:"Count,omitempty"`

	DeviceIDs []string `json:"DeviceIDs,omitempty"`

	// A list of capabilities; an OR list of AND lists of capabilities.
	Capabilities [][]string `json:"Capabilities,omitempty"`

	// Driver-specific options, specified as a key/value pairs. These options are passed directly to the driver.
	Options map[string]string `json:"Options,omitempty"`
}
