/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ContainerLogsOpts struct {
	Id         string `uri:"id" binding:"required"`
	Context    string `form:"context"`
	Follow     bool   `form:"follow,default=false"`
	Stdout     bool   `form:"stdout,default=false"`
	Stderr     bool   `form:"stderr,default=false"`
	Since      int    `form:"since,default=0"`
	Until      int    `form:"until,default=0"`
	Timestamps bool   `form:"timestamps,default=false"`
	Tail       string `form:"tail,default=all"`
}
