/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ImageCommitOpts struct {
	ContainerConfig
	Context   string   `form:"context"`
	Container string   `form:"container"`
	Repo      string   `form:"repo"`
	Tag       string   `form:"tag"`
	Comment   string   `form:"comment"`
	Author    string   `form:"author"`
	Pause     bool     `form:"pause,default=true"`
	Changes   []string `form:"changes"`
}
