/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type MemoryStats struct {
	Usage uint64 `json:"Usage,omitempty"`

	MaxUsage uint64 `json:"MaxUsage,omitempty"`

	Stats map[string]uint64 `json:"Stats,omitempty"`

	Failcnt uint64 `json:"Failcnt,omitempty"`

	Limit uint64 `json:"Limit,omitempty"`

	Commit uint64 `json:"Commit,omitempty"`

	CommitPeak uint64 `json:"CommitPeak,omitempty"`

	PrivateWorkingSet uint64 `json:"PrivateWorkingSet,omitempty"`
}
