/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type InlineObject6 struct {

	// Assign a nem to the container.
	Name string `json:"Name,omitempty"`

	// Override the entrypoint of the image.
	Entrypoint []string `json:"Entrypoint,omitempty"`

	// A list of environment variables in the form `[\"VAR=value\", ...]`.
	Environment []string `json:"Environment,omitempty"`

	// A list of labels to override or add in the form `[\"LABEL=value\", ...]`.
	Labels map[string]string `json:"Labels,omitempty"`

	// Run as specified username or uid.
	User string `json:"User,omitempty"`

	// Start linked services.
	Deps bool `json:"Deps,omitempty"`

	// Remove contaiiner after run. Ignored in detached mode.
	Remove bool `json:"Remove,omitempty"`

	// Publish a container's port(s) to the host.
	Publish []string `json:"Publish,omitempty"`

	// Run command with the service's ports enabled and mapped to the host.
	ServicePorts bool `json:"ServicePorts,omitempty"`

	// Use the service's network aliases in the network(s) the container connects to.
	UseAliases bool `json:"UseAliases,omitempty"`

	// Bind mount volumes
	Volume []string `json:"Volume,omitempty"`

	// Disable pseudo-tty allocation. By default `docker-compose run` allocates a TTY.
	Tty bool `json:"Tty,omitempty"`

	// Working directory inside the container.
	Workdir string `json:"Workdir,omitempty"`

	// Working directory inside the container.
	Command []string `json:"Command,omitempty"`
}
