/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ContainersIdStatsNetworks struct {
	RxBytes uint64 `json:"RxBytes,omitempty"`

	RxPackets uint64 `json:"RxPackets,omitempty"`

	RxErrors uint64 `json:"RxErrors,omitempty"`

	RxDropped uint64 `json:"RxDropped,omitempty"`

	TxBytes uint64 `json:"TxBytes,omitempty"`

	TxPackets uint64 `json:"TxPackets,omitempty"`

	TxErrors uint64 `json:"TxErrors,omitempty"`

	TxDropped uint64 `json:"TxDropped,omitempty"`

	EndpointId string `json:"EndpointId,omitempty"`

	InstanceId string `json:"InstanceId,omitempty"`
}
