/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ImageBuildOpts struct {
	Context     string   `form:"context"`
	Dockerfile  string   `form:"dockerfile,default=Dockerfile"`
	Tags        []string `form:"tags"`
	Extrahosts  []string `form:"extrahosts"`
	Remote      string   `form:"remote"`
	Quiet       bool     `form:"quiet,default=false"`
	Nocache     bool     `form:"nocache,default=false"`
	Cachefrom   []string `form:"cachefrom"`
	Pull        bool     `form:"pull"`
	Remove      bool     `form:"remove,default=true"`
	ForceRemove bool     `form:"forceremove,default=false"`
	Memory      int64    `form:"memory"`
	Memswap     int64    `form:"memswap"`
	Cpushares   int64    `form:"cpushares"`
	Cpusetcpus  string   `form:"cpusetcpus"`
	Cpuperiod   int64    `form:"cpuperiod"`
	Cpuquota    int64    `form:"cpuquota"`
	Buildargs   string   `form:"buildargs"`
	Shmsize     int64    `form:"shmsize"`
	Squash      bool     `form:"squash"`
	Labels      string   `form:"labels"`
	Networkmode string   `form:"networkmode"`
	Platform    string   `form:"platform"`
	Target      string   `form:"target"`
	Outputs     string   `form:"outputs"`
}
