/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// PluginConfig - The config of a plugin.
type PluginConfig struct {

	// Docker Version used to create the plugin
	DockerVersion string `json:"DockerVersion,omitempty"`

	Description string `json:"Description"`

	Documentation string `json:"Documentation"`

	Interface PluginConfigInterface `json:"Interface"`

	Entrypoint []string `json:"Entrypoint"`

	WorkDir string `json:"WorkDir"`

	User PluginConfigUser `json:"User,omitempty"`

	Network PluginConfigNetwork `json:"Network"`

	Linux PluginConfigLinux `json:"Linux"`

	PropagatedMount string `json:"PropagatedMount"`

	IpcHost bool `json:"IpcHost"`

	PidHost bool `json:"PidHost"`

	Mounts []PluginMount `json:"Mounts"`

	Env []PluginEnv `json:"Env"`

	Args PluginConfigArgs `json:"Args"`

	Rootfs PluginConfigRootfs `json:"rootfs,omitempty"`
}
