/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ImageSummary struct {
	Id string `json:"Id"`

	ParentId string `json:"ParentId"`

	RepoTags []string `json:"RepoTags"`

	RepoDigests []string `json:"RepoDigests"`

	Created int64 `json:"Created"`

	Size int64 `json:"Size"`

	SharedSize int64 `json:"SharedSize"`

	VirtualSize int64 `json:"VirtualSize"`

	Labels map[string]string `json:"Labels"`

	Containers int64 `json:"Containers"`
}
