/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Image struct {
	Id string `json:"Id"`

	RepoTags []string `json:"RepoTags,omitempty"`

	RepoDigests []string `json:"RepoDigests,omitempty"`

	Parent string `json:"Parent"`

	Comment string `json:"Comment"`

	Created string `json:"Created"`

	Container string `json:"Container"`

	ContainerConfig ContainerConfig `json:"ContainerConfig,omitempty"`

	DockerVersion string `json:"DockerVersion"`

	Author string `json:"Author"`

	Config ContainerConfig `json:"Config,omitempty"`

	Architecture string `json:"Architecture"`

	Os string `json:"Os"`

	OsVersion string `json:"OsVersion,omitempty"`

	Size int64 `json:"Size"`

	VirtualSize int64 `json:"VirtualSize"`

	GraphDriver GraphDriverData `json:"GraphDriver"`

	RootFS ImageRootFs `json:"RootFS"`

	Metadata ImageMetadata `json:"Metadata,omitempty"`
}
