/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ProjectUpOpts struct {
	Name                 string   `uri:"name" binding:"required"`
	Context              string   `form:"context"`
	Services             []string `form:"services"`
	Detach               bool     `form:"detach,default=false"`
	Build                bool     `form:"build,default=false"`
	NoBuild              bool     `form:"nobuild,default=false"`
	RemoveOrphans        bool     `form:"removeorphans,default=false"`
	Scale                string   `form:"scale"`
	ForceRecreate        bool     `form:"forcerecreate,default=false"`
	Recreate             bool     `form:"recreate,default=true"`
	Start                bool     `form:"start,default=true"`
	AbortOnContainerExit bool     `form:"abortoncontainerexit,default=false"`
	ExitCodeFrom         string   `form:"exitcodefrom"`
	Timeout              *int64   `form:"timeout,default=10"`
	Deps                 bool     `form:"deps,default=true"`
	AlwaysRecreateDeps   bool     `form:"alwaysrecreatedeps,default=false"`
	RenewAnonVolumes     bool     `form:"renewvolumes,default=false"`
	AttachDeps           bool     `form:"attachdeps,default=false"`
	QuietPull            bool     `form:"quietpull,default=false"`
	AbortExit            bool     `form:"abortexit,default=false"`
	Attach               []string `form:"attach"`
}
