/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Network struct {
	Name string `json:"Name,omitempty"`

	Id string `json:"Id,omitempty"`

	Created string `json:"Created,omitempty"`

	Scope string `json:"Scope,omitempty"`

	Driver string `json:"Driver,omitempty"`

	EnableIPv6 bool `json:"EnableIPv6,omitempty"`

	IPAM Ipam `json:"IPAM,omitempty"`

	Internal bool `json:"Internal,omitempty"`

	Attachable bool `json:"Attachable,omitempty"`

	Ingress bool `json:"Ingress,omitempty"`

	Containers map[string]NetworkContainer `json:"Containers,omitempty"`

	Options map[string]string `json:"Options,omitempty"`

	Labels map[string]string `json:"Labels,omitempty"`
}
