/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// InlineObject5 - Configuration for a context that is portable between hosts
type InlineObject5 struct {

	// A description of the context.
	Description string `json:"Description,omitempty"`

	// The host for the docker endpoint.
	Docker map[string]string `json:"Docker,omitempty"`
}
