/*
 * GoPort API
 *
 * The GoPort API extends the Docker Engine API to connect to remote Hosts by serving a context endpoint. It also adds the ability to manage docker-compose projects.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:  ``` {   \"message\": \"page not found\" } ```
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// PluginsInfo - Available plugins per type.  <p><br /></p>  > **Note**: Only unmanaged (V1) plugins are included in this list. > V1 plugins are \"lazily\" loaded, and are not returned in this list > if there is no resource using the plugin.
type PluginsInfo struct {

	// Names of available volume-drivers, and network-driver plugins.
	Volume []string `json:"Volume,omitempty"`

	// Names of available network-drivers, and network-driver plugins.
	Network []string `json:"Network,omitempty"`

	// Names of available authorization plugins.
	Authorization []string `json:"Authorization,omitempty"`

	// Names of available logging-drivers, and logging-driver plugins.
	Log []string `json:"Log,omitempty"`
}
